# Generated by Django 3.2.4 on 2021-07-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContacktsProwork',
            new_name='ContactsProwork',
        ),
        migrations.RenameModel(
            old_name='SuccessProjects',
            new_name='SuccessProject',
        ),
        migrations.RenameModel(
            old_name='SuccessProjectsTranslation',
            new_name='SuccessProjectTranslation',
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='successprojecttranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'success project Translation'},
        ),
        migrations.AlterModelTable(
            name='successprojecttranslation',
            table='basic_successproject_translation',
        ),
    ]
