# Generated by Django 3.2.4 on 2021-07-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20210708_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.country'),
        ),
    ]
