# Generated by Django 3.2.4 on 2021-07-09 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_alter_startapper_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startapper',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startapper', to=settings.AUTH_USER_MODEL),
        ),
    ]
