# Generated by Django 3.2.4 on 2021-07-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_alter_startapper_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='post_image',
            field=models.ImageField(upload_to='about_us/'),
        ),
        migrations.AlterField(
            model_name='allusersidea',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='alluser_ideas/'),
        ),
        migrations.AlterField(
            model_name='applicationstaff',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='media_staff_resume/'),
        ),
        migrations.AlterField(
            model_name='ideastartapper',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='startapper_idea/'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_image/'),
        ),
        migrations.AlterField(
            model_name='startapper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='startappper_image/'),
        ),
        migrations.AlterField(
            model_name='successproject',
            name='image',
            field=models.ImageField(null=True, upload_to='projects_photo/'),
        ),
    ]
